### ISSUE TITLE
Feature request: Pull from upstream

### ISSUE THREAD

**Issue by mal-tee** [baltpeter/CyberChef#2]

**Comment by baltpeter** [comment]
Did that at the end of last year, and there haven't been any changes upstream since, so I'll close this.

Feel free to reopen or create a new issue if there are any upstream changes you'd like to see deployed.

**Comment by mal-tee** [comment]
They released a new major version: 

https://github.com/gchq/CyberChef/wiki/Character-encoding,-EOL-separators,-and-editor-features

**Comment by baltpeter** [comment]
Cool stuff. Updated.
